# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Luiz E. Hupalo
title: R&D Researcher @ Instituto Nacional de Telecomunicações - INATEL
email: lhpzl@protonmail.com
# email_title: Email (Email title override)
# phone: 
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: jekyllrb
github_username:  lhupalo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: lzhpl
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
googlescholar_username: sZygoGQAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# # - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  🎓 M.Sc. in Communications and Signal Processing at Universidade Federal de Santa Catarina (2023)<br>🔎 R&D Researcher at Instituto Nacional de Telecomunicações<br>🔭 O-RAN, 5G, Self-Organizing Networks, and NS-3 simulations<br>👯 I'm looking to collaborate on the future wireless networks<br>🌱 I'm currently researching on how to leverage Reinforcement Learning to optimize traffic in 5G networks<br>⚙️ Working to build and deploy models through xApps in the near-RT RIC


content:
  - title: Research # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Masters Thesis
        # link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # link_text: Link Text
        additional_links:
          - title:  Code
            icon: fab fa-github
            url: https://github.com/lhupalo/ranslicing
        quote: >
          "Physical Layer Network Slicing for eMBB and mMTC with Distributed Power Allocation"
        description: | # this will include new lines to allow paragraphs
          Technique to adapt the transmission power of the mMTC devices in the uplink in a decentralized fashion, without the need of coordination between BS and UE. Roughly speaking, this is done through the creation of "clusters" of the received SNR seen at the BS, i.e., by adapting the mMTC device transmission power we can artificially create more than one SNR mean seen at the BS.
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title:  Undergraduation Thesis
        # link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # link_text: Link Text
        additional_links:
          - title:  Code
            icon: fab fa-github
            url: https://github.com/lhupalo/oil-prediction
          - title: Document
            icon: fab fa-elementor
            url: https://repositorio.ufsc.br/bitstream/handle/123456789/202398/TCC_LuizEduardoHupalo.pdf?sequence=1&isAllowed=y
        quote: >
          "Modelos aproximados para predição de variáveis de poços de petróleo"
        description: | # this will include new lines to allow paragraphs
          Use of autoregressive linear models based on systems identification to predict the short term values of the production of oil wells from simulated reseirvoirs. The simulations were performed through the MRST (SINTEF).
  # - title: Publications
  #   layout: list
  #   content:
  #     - layout: right
  #       title: Company name
  #       sub_title: Job title
  #       caption: Date Range (eg. November 2016 - present)
  #       link: Link to company (optional)
  #       quote: >
  #         Short description of the company (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description of role
  # - title: Education
  #   layout: list
  #   content:
  #     - layout: top-right
  #       title: Institution name
  #       sub_title: Qualifications (eg. BA Performing Arts)
  #       caption: Date Range (eg. 2016 - 2019)
  #       quote: >
  #         Short institution or course description (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description of qualification
  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

  #     Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
